### ISSUE TITLE
Remove requirements for words file for annotation preparation

### ISSUE THREAD

**Issue by annajung** [vmware-labs/ml-conversational-analytic-tool#4]
### **Description**
When running `featureVector.py` to prepare data for annotation, `words` argument is required even though it's not being used.

Remove requirements for `words` file when running `featureVector.py` with `-unannotated` flag and make `words` file required when running `featureVector.py` **without** `-unannotated` flag

This would allow users to run `python featureVector.py <rawdatafile> -unannotated` instead of `python featureVector.py <rawdatafile> <words> -unannotated`

### **Possible Solution**
- Set default to argument words
- Input validation based on arguments passed in

### **Steps to Reproduce**
To reproduce the error, run the following
```
python featureVector.py <rawdatafile> <words> -unannotated
```

**Comment by difince** [comment]
It seems to me that <words> could be an optional parameter as well?

**Comment by annajung** [comment]
Yeah, I think you have to make it optional to achieve the following
```
python featureVector.py <rawdatafile> -unannotated
```

**Comment by difince** [comment]
IMO, commands like these below are ambiguous. **Unannotated** is doing something totally different than the other two commands. It "forms a conversation string by given communication on a pull request", meanwhile the other two are creating a feature matrix.
```
python featureVector.py <rawdatafile> -unannotated
python featureVector.py <rawdatafile> <wordsfile> 
python featureVector.py <rawdatafile> 
```

So, I am suggesting restructuring the entire command to something like this: 
```
python featureVector.py  featurize -f <rawfile>   
python featureVector.py  featurize -f <rawfile> -w <wordsfile>

python featureVector.py  preprocess -f <rawfile>

```
@annajung WDYT?

**Comment by annajung** [comment]
I don't think this is a valid command `python featureVector.py <rawdatafile>`

Currently `featureVector` requires either `-unannotated` or `words` file. 
So there are two cases to call `featureVector`
- to create a feature vector using words file
- to reformat the data for annotation

I agree that unannotated functionality is better off on its own. I would even go further to extract out the annotation part out of featureVector on it's own. I think that would help reduce ambiguousness. WDYT?

**Comment by difince** [comment]
I see `words` more as an optional argument for creating a feature matrix than a mandatory one. 
If there are no words you are interested in, it makes sense for me to be able to create a feature matrix based on the sentiment score and number of comments only?  

yes, agree on moving the reformat functionality out of veatureVector ..I was considering this s an option as well.

**Comment by annajung** [comment]
>If there are no words you are interested in, it makes sense for me to be able to create a feature matrix based on the sentiment score and number of comments only by executing python featureVector.py <rawfile> or providing a words file that has no words. WDYT?

I see what you're saying and yeah I agree. I believe it doesn't work that way right now but that makes sense especially since we already have the sentiment and code blocks as default features.

**Comment by difince** [comment]
yes, currently it will fail, but with a slight change, we can make it work. You got my idea.
